data:
  message: '{cipher}f2204dfd18978f75aed6e6733ea585ef3adf914a3096692a51b7a973f1132ea9'
spring:
  application:
    name: test
  cloud:
    inetutils:
      preferred-networks: 127.0.0.1
server:
  port: 9998
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://admin:admin123@node1:8100/eureka/
